development:
  adapter: async
  # adapter: redis
  # url: redis://localhost:6379/1
  # channel_prefix: deploy_app_to_heroku_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_PROVIDER'] %>
  channel_prefix: deploy_app_to_heroku_production
